# The joint state controller handles publishing transforms for any moving joints
gazebo:
   joint_state_controller:
      type: "joint_state_controller/JointStateController"
      publish_rate: 50

   joint_fl_controller:
      type: velocity_controllers/JointVelocityController
      joint: axleFront_link_2_wheelFrontLeft_link
      pid: {p: 5.0, i: 0, d: 0}
   
   joint_fr_controller:
      type: velocity_controllers/JointVelocityController
      joint: axleFront_link_2_wheelFrontRight_link
      pid: {p: 5.0, i: 0, d: 0}
   
   joint_rl_controller:
      type: velocity_controllers/JointVelocityController
      joint: axleRear_link_2_wheelRearLeft_link
      pid: {p: 5.0, i: 0, d: 0}
   
   joint_rr_controller:
      type: velocity_controllers/JointVelocityController
      joint: axleRear_link_2_wheelRearRight_link
      pid: {p: 5.0, i: 0, d: 0}

   body_angle_controller:
      type: velocity_controllers/JointVelocityController
      joint: jointFront_link_2_jointRear_link
      pid: {p: 5.0, i: 0, d: 0}

   swing_angle_controller:
      type: velocity_controllers/JointVelocityController
      joint: axleFront_link_2_jointFront_link
      pid: {p: 5.0, i: 0, d: 0}
   
gazebo_ros_control:
   pid_gains:
      axleFront_link_2_wheelFrontLeft_link: {p: 10.0, i: 1, d: 0}
      axleFront_link_2_wheelFrontRight_link: {p: 10.0, i: 1, d: 0}
      axleRear_link_2_wheelRearLeft_link: {p: 10.0, i: 1, d: 0}
      axleRear_link_2_wheelRearRight_link: {p: 10.0, i: 1, d: 0}
      jointFront_link_2_jointRear_link: {p: 1.0, i: 0, d: 0}
      axleFront_link_2_jointFront_link: {p: 1.0, i: 0, d: 0}
